fauna/fauna-dotnet

- concourse/scripts/publish.sh
> Add nuget publish script

- Fauna.Test/Linq/Query.Tests.cs
- Fauna/Linq/PipelineBuilder.cs
> fix local var references

- Fauna.Test/Helpers/Fixtures.cs
- Fauna.Test/Query.Tests.cs
- Fauna/Query/Query.cs
> Fix const string interpolations

- Fauna.Test/Helpers/Fixtures.cs
- Fauna.Test/Integration.Tests.cs
- Fauna/Client/IClient.cs
- README.md
See readme updates for details.
> Add embedded set support

- Fauna.Test/Linq/Query.Tests.cs
- Fauna/Linq/IQuerySource.cs
- Fauna/Linq/PipelineExecutor.cs
- Fauna/Linq/QuerySource.cs
- Fauna/Linq/QuerySourceDsl.cs
- Fauna/Linq/QuerySourceExtensions.cs
- Fauna/Linq/QuerySourceToCollections.cs
> All the cancellation

- Fauna.Test/Linq/Query.Tests.cs
- Fauna/Linq/IQuerySource.cs
- Fauna/Linq/PipelineExecutor.cs
- Fauna/Linq/QuerySource.cs
- Fauna/Linq/QuerySourceDsl.cs
- Fauna/Linq/QuerySourceExtensions.cs
- Fauna/Linq/QuerySourceToCollections.cs
> Add LINQ Single methods

- concourse/scripts/publish.sh
This will be temporary until i get docs to publish
> Skip duplicates during publish

- Fauna/Client/Client.cs
- Fauna/Client/Configuration.cs
- Fauna/Client/Connection.cs
- Fauna/Client/IConnection.cs
- Fauna/Client/PaginationExtensions.cs
- Fauna/Client/QueryOptions.cs
- Fauna/Client/RetryConfiguration.cs
- Fauna/Mapping/FieldInfo.cs
- Fauna/Mapping/FieldName.cs
- Fauna/Mapping/MappingContext.cs
- Fauna/Mapping/MappingInfo.cs
* Add missing documentation
* Small naming adjustments for clarity/simplicity.
> Add some missing documentation

- concourse/scripts/publish-docs.sh
This is super basic, but low effort and works.
Current look:
> Add index page for gh-pages

- Fauna/Fauna.csproj
Increment package version to 0.2.0-beta
* Remove `NullDocumentRef` and `NullNamedDocumentRef` non-generic classes. These did not allow users to safely make typed queries for documents when a null document might be returned. For example, when calling `client.QueryAsync<Document>(...)`, receiving a null document from Fauna would trigger a serialization exception because a `NullDocumentRef` is not a `Document`.
* Add `NullableDocument<>` abstract class with `NullDocument<>` and `NonNullDocument<>` concrete classes. Users can now query for `NullableDocument<Document>`, `NullableDocument<NamedDocument>`, `NullableDocument<DocumentRef>`, `NullableDocument<NamedDocumentRef>`, and `NullableDocument<MyPOCO>` and receive concrete `NullDocument<>` and `NonNullDocument<>` instances in their results. …
> Release 0.2.0-beta

- Fauna.Test/Util/ExpressionSwtich.Tests.cs
- Fauna.Test/Util/Expressions.Tests.cs
- Fauna.Test/Util/TypeExtensions.Test.cs
> Add Unit Tests for Utils

- Fauna.Test/Helpers/Fixtures.cs
- Fauna.Test/Linq/Query.Tests.cs
- Fauna/Linq/IQuerySource.cs
- Fauna/Linq/QuerySourceDsl.cs
- Fauna/Linq/QuerySourceExtensions.cs
> Add Average LINQ methods

- Fauna.Test/Serialization/Deserializer.Tests.cs
- Fauna.Test/Serialization/RoundTrip.Tests.cs
- Fauna.Test/Serialization/Serializer.Tests.cs
- Fauna/Client/Client.cs
- Fauna/Linq/DataContext.cs
- Fauna/Linq/DataContextBuilder.cs
- Fauna/Linq/IntermediateQueryHelpers.cs
- Fauna/Linq/LookupTable.cs
- Fauna/Linq/Pipeline.cs
- Fauna/Linq/PipelineExecutor.cs
- Fauna/Linq/SubQuerySwitch.cs
- Fauna/Mapping/MappingContext.cs
- Fauna/Query/IQueryFragment.cs
- Fauna/Query/QueryStringHandler.cs
- Fauna/Serialization/CheckedDeserializer.cs
- Fauna/Serialization/ClassDeserializer.cs
- Fauna/Serialization/Deserializer.cs
- Fauna/Serialization/DictionaryDeserializer.cs
- Fauna/Serialization/DocumentDeserializer.cs
- Fauna/Serialization/DynamicDeserializer.cs
- Fauna/Serialization/ListDeserializer.cs
- Fauna/Serialization/NullableDocumentDeserializer.cs
- Fauna/Serialization/PageDeserializer.cs
- Fauna/Serialization/Serializer.cs
- Fauna/Types/NamedRef.cs
- Fauna/Types/Ref.cs
While working through another PR, I noticed some cruft and naming inconsistencies that should be cleaned up.
Clean it up! And do it without introducing behavior changes.
> Fix interface naming and other cleanup

- .github/pull_request_template.md
Adds bullets before the checkboxes so that GitHub doesn't treat it like a task list.
We don't want that workflow.
Manually updated this PR with the new template
----
> Disable checklist in PR template

- .github/workflows/pr_format.yml
- .github/workflows/pr_validate.yml
Updating the triggers so we don't run the workflows when updating the README for example
----
> ci: Update workflow triggers

- Fauna.Test/Helpers/Fixtures.cs
- Fauna.Test/Integration.Tests.cs
- Fauna/Client/Client.cs
- Fauna/Client/Connection.cs
- Fauna/Client/Events.cs
- Fauna/Client/IClient.cs
- Fauna/Client/IConnection.cs
- Fauna/Client/RetryConfiguration.cs
- Fauna/Client/Streaming.cs
- Fauna/Exceptions/FaunaException.cs
- Fauna/Linq/DataContext.cs
- Fauna/Types/Stream.cs
- README.md
- Add support for [Stream](https://docs.fauna.com/fauna/current/reference/streaming/)
- Users should be able to open and subscribe to Streams with events deserialized into types.
- Added integration tests
> feat: Add Streaming support

- .github/workflows/pr_coverage.yml
- Fauna.Test/Configuration.Tests.cs
Testing GHA changes in a separate branch
> Testing GHA changes

- Fauna.Test/Helpers/Fixtures.cs
- Fauna.Test/Integration.Tests.cs
- Fauna.Test/Linq/Context.Tests.cs
- Fauna.Test/Linq/ContextValidation.Tests.cs
- Fauna.Test/Serialization/RoundTrip.Tests.cs
- Fauna.Test/Serialization/Serializers/ClassSerializer.Tests.cs
- Fauna.Test/Serialization/TestClasses.cs
- Fauna/Mapping/Attributes.cs
- Fauna/Mapping/FieldInfo.cs
- Fauna/Mapping/FieldType.cs
- Fauna/Mapping/MappingInfo.cs
- Fauna/Serialization/ClassSerializer.cs
- README.md
* Add Id, Ts, Coll, and Ignore attributes
* Remove Object attribute
BT-5111
We were using fallible and confusing logic to determine when to serialize Id, Coll, and Ts properties. Instead, we want to let users control how class properties are serialized.
Updated unit tests
* - [X] Breaking change (backwards-incompatible fix or feature)
* - [X] My change requires a change to the README, and I have updated it accordingly.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Add Id, Ts, Coll, and Ignore attributes

- .gitignore
- Fauna.Test/Exceptions/ServiceException.Tests.cs
- Fauna.Test/Fauna.Test.csproj
- Fauna.Test/Helpers/TestClientHelper.cs
- Fauna.Test/Integration.Tests.cs
- Fauna.Test/Linq/Context.Tests.cs
- Fauna.Test/Linq/ContextValidation.Tests.cs
- Fauna.Test/Linq/Query.Tests.cs
- Fauna.Test/Performance/MetricsHandler.cs
- Fauna.Test/Performance/Performance.Tests.cs
- Fauna.Test/Performance/TestDataModels.cs
- Fauna.Test/Performance/TestDataParser.cs
- Fauna.Test/Performance/TestQueryExtensions.cs
- Fauna.Test/Performance/setup/fauna/main.fsl
- Fauna.Test/Performance/setup/fauna/seeddata.fql
- Fauna.Test/Performance/setup/init.sh
- Fauna.Test/Performance/setup/queries.json
- Fauna.Test/Performance/setup/teardown.sh
- concourse/pipeline.yml
- concourse/scripts/perf.sh
- concourse/tasks/perf.yml
This adds perf tests under a separate test category that run a set of queries from a static file, measures the "non-query time" (i.e. driver overhead), and outputs the `P50/P95/P99/StdDev` for the data points in a text file to be sent to a Slack channel or whatever.  Support for shipping to Datadog has also been added, but is not currently being used.
Each perf test in the json file has the following pieces:
- A name for the test scenario
- Query parts to be used in query composition
- Whether the result is from the `Product` collection from the FSL file (and modeled in `TestDataModels.cs`)
- If true, the test should deserialize the return object(s)
- Whether the result returns multiple pages of data
- If true, the test will paginate through all the results and measure the overall time …
> feat(perf-tests): Add Performance tests and run them regularly in release pipeline

- concourse/scripts/perf.sh
Two more tiny fixes:
- Make `apt` even quieter
- Don't overwrite all the `echo`s with the last one 😖 
----
> fix(perf-tests): One more Concourse fix

- Fauna.Test/E2E/E2EErrorHandling.Test.cs
- Fauna.Test/Exceptions/ServiceException.Tests.cs
- Fauna/Client.cs
- Fauna/Core/Connection.cs
- Fauna/Core/ErrorInfo.cs
- Fauna/Core/QueryResponse.cs
- Fauna/Core/ResponseFields.cs
- Fauna/Exceptions/AbortException.cs
- Fauna/Exceptions/AuthenticationException.cs
- Fauna/Exceptions/AuthorizationException.cs
- Fauna/Exceptions/BadGatewayException.cs
- Fauna/Exceptions/ConstraintFailure.cs
- Fauna/Exceptions/ConstraintFailureException.cs
- Fauna/Exceptions/ContendedTransactionException.cs
- Fauna/Exceptions/ExceptionHandler.cs
- Fauna/Exceptions/IRetryableException.cs
- Fauna/Exceptions/InvalidRequestException.cs
- Fauna/Exceptions/NetworkException.cs
- Fauna/Exceptions/QueryCheckException.cs
- Fauna/Exceptions/QueryRuntimeException.cs
- Fauna/Exceptions/QueryTimeoutException.cs
- Fauna/Exceptions/ServiceException.cs
- Fauna/Exceptions/ThrottlingException.cs
- Fauna/Exceptions/TimeoutException.cs
- Fauna/IClient.cs
* Break out exceptions into separate files for easier management
* Add ConstraintFailureException, parsing, and test. This is imperfect in that it we end up with JsonElement types for the path elements, but this gets us to a spot where users can take action which is probably good enough for now.
* Rename ExceptionFactory to ExceptionHandler
* Renames some exception classes to align with Java 
* Align C# exceptions with Java exceptions
* We didn't handle constraint failures.
* - [X] New feature (non-breaking change that adds functionality)
* - [X] Breaking change (backwards-incompatible fix or feature)
* - [ ] My …
> Align exceptions and support constraint failures

- .github/workflows/pr_format.yml
- .github/workflows/pr_validate.yml
Update the GitHub actions versions
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-dotnet@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
N/A
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> chore(github-actions): Update Marketplace Actions

- Fauna/Fauna.csproj
Release 0.3.0-beta!
* - [X] New feature (non-breaking change that adds functionality)
* - [X] Breaking change (backwards-incompatible fix or feature)
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.
----
> release: 0.3.0-beta

- Fauna/Fauna.csproj
This reverts commit fff7479d48ef7e82ba646fe00db834a87d59174c.
> Revert "release: 0.3.0-beta (#187)"

- concourse/scripts/perf.sh
Just a quick fix to the perf tests since v3 of the `fauna-shell` breaks the pipeline.
----
> fix(perf-tests): Pin to fauna-shell@2.x

- Fauna/Fauna.csproj
Bumping version to `0.4.0-beta`...
That's it, that's the change.
----
> chore(version): Bump version to 0.4.0-beta

- README.md
Notes that the LINQ functionality is in preview and may change in future releases.
Sets users expectations about support while in beta.
We're removing LINQ refs from docs.fauna.com with https://github.com/fauna/docs.fauna.com/pull/2533.
N/A
----
> [DOCS-3652] Note LINQ API is in preview

- Fauna/Fauna.csproj
> Release 0.5.0-beta

- Fauna.Test/Integration.Tests.cs
- Fauna.Test/Serialization/Helpers.cs
- Fauna.Test/Serialization/Serializers/TypedSerializer.Tests.cs
- Fauna/Client.cs
- Fauna/Core/Connection.cs
- Fauna/Core/IConnection.cs
- Fauna/Core/StreamEnumerable.cs
- Fauna/IClient.cs
- Fauna/Linq/DataContext.cs
- Fauna/Serialization/EventSourceSerializer.cs
- Fauna/Serialization/Serializer.cs
- Fauna/Serialization/TokenType.cs
- Fauna/Serialization/Utf8FaunaReader.cs
- Fauna/Types/EventSource.cs
ENG-6824
Rename `Stream` to `EventSource`
Alignment with the wire protocol and the other drivers
Integration tests
* - [x] Breaking change (backwards-incompatible fix or feature)
----
> feat: Rename Stream to EventSource

- README.md
Closes a code block in the README.
The code block currently eats the Event Streams section:
N/A
----
> docs: README fix

- Fauna/Fauna.csproj
v1.0.0 release (https://faunadb.atlassian.net/browse/BT-5280)
----
> chore(release): Update to v1.0.0 for GA release

- Fauna/Fauna.csproj
There was one last fix waiting in the wings (#225 ) that hadn't merged before 1.0.0 released, so this is a patch release to get that fix out.
----
> Release 1.0.1
