fauna/fauna-dotnet

Fauna.Test/Serialization/Deserializer.Tests.cs, Fauna.Test/Serialization/Utf8FaunaReader.Tests.cs, Fauna/Serialization/Deserializer.cs, Fauna/Serialization/Utf8FaunaReader.cs
Instead of deserializing `@date` to DateTime, we should deserialize to DateOnly.
Ideally we'd be able to handle date and time variants, i.e. if a user specifies a DateTime type for a `@date` we would do that, but I don't think that's necessary for beta. It does maintain an asymmetry where users can serialize date/time types to whatever they choose, but cannot deserialize them as they choose.
=> @date as DateOnly

Fauna/Serialization/Serializer.cs
Type hint is an implementation detail of the MappingContext, so remove it from the external contract.
=> Remove type hint from public serialize contract

concourse/scripts/publish-docs.sh
We're in the docs clone when we try to get the git tags, which don't exist there. Instead, use the _real_ repo.
=> Fix all versions list

README.md
Ticket(s): [DOCS-2825](https://faunadb.atlassian.net/browse/DOCS-2825)
Removes class names from method references in text. This aligns with Google's [style recommendations](https://developers.google.com/style/code-in-text#method-names).
[DOCS-2825]: https://faunadb.atlassian.net/browse/DOCS-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-2825] README: Remove class names in method refs

Fauna.Test/Serialization/Deserializer.Tests.cs, Fauna.Test/Serialization/Serializer.Tests.cs, Fauna.Test/Serialization/TestClasses.cs, Fauna/Mapping/FieldInfo.cs, Fauna/Serialization/Deserializer.cs, Fauna/Serialization/NullableStructDeserializer.cs
When deserializing into a nullable struct, the deserializer falls through and fails. This was masked in unit tests because the nullable unit test uses GenerateNullable directly rather than going through the primary deserialize path.
```
System.ArgumentException : Unsupported deserialization target type System.Nullable`1[System.Int32]
```
At first I tried to build and use a NullableDeserializer in the primary deserialize entry point, but the default(T) behavior resulted in a Nullable<int> to be set to 0 in the null case. After several attempts at getting this to work, I worked on a separate solution.
Implement NullableStructDeserializer that constrains the generic to structs. This allowed the default case to return a new Nullable<T>, which results in the expected behavior.
=> Add support for nullable struct deserialization

Fauna.Test/Serialization/Serializer.Tests.cs, Fauna.Test/Serialization/TestClasses.cs, Fauna/Mapping/Attributes.cs, Fauna/Mapping/FieldInfo.cs, Fauna/Serialization/Serializer.cs
After some deliberation, we decided that supporting a type override attribute is overkill at this point. Types in C# map comfortably to Fauna, so exposing this allows users to do something they probably _shouldn't be doing_, such as modeling an unsigned short and storing it as a long.
* Remove FaunaType attribute
* Remove handling of FaunaType attribute in Serializer
* Remove tests specifics to FaunaType overrides
* Add extreme values tests for ushort, uint, and float
=> Remove FaunaType override attribute

Fauna.Test/Serialization/RoundTrip.Tests.cs, Fauna/Serialization/Deserializer.cs, Fauna/Serialization/NumberDeserializers.cs, Fauna/Serialization/Utf8FaunaReader.cs
Deserialization is motivated by the Fauna token it interacts with, not the target type. This is reasonable for a default case where we don't know what type we want, but when we know, we should use the right deserializer.
Continue down the path of using dedicated deserializers for known types.
=> Roundtrip short and ushort serialization

Fauna.Test/Serialization/Deserializer.Tests.cs, Fauna.Test/Serialization/RoundTrip.Tests.cs, Fauna/Serialization/Deserializer.cs, Fauna/Serialization/NumberDeserializers.cs, Fauna/Serialization/Utf8FaunaReader.cs
Users couldn't roundtrip numbers because we were using the FaunaToken to drive deserialization rather than the target type.
* Use dedicated deserializers for number types to make numbers roundtrippable.
=> Use type-driven deserialization for all numbers

Fauna.Test/Serialization/Deserializer.Tests.cs, Fauna.Test/Serialization/RoundTrip.Tests.cs, Fauna.Test/Serialization/Serializer.Tests.cs, Fauna.Test/Serialization/TestClasses.cs, Fauna/Serialization/Serializer.cs
We didn't handle serialization of documents and named documents.
* Add serialization support for
* Document, DocumentRef, NamedDocument, NamedDocumentRef
* NullableDocument<> for each of the above
* Fix roundtrip test ordering
* Add roundtrip tests that show that we don't roundtrip classes as documents
=> Serialize document types

Fauna.Test/Helpers/Fixtures.cs, Fauna.Test/Linq/Context.Tests.cs, Fauna.Test/Linq/Query.Tests.cs, Fauna.Test/Serialization/Deserializer.Tests.cs, Fauna/Linq/DataContext.cs, Fauna/Linq/DataContextBuilder.cs, Fauna/Linq/IntermediateQueryHelpers.cs, Fauna/Linq/QuerySourceDsl.cs, Fauna/Linq/SubQuerySwitch.cs, Fauna/Serialization/ListDeserializer.cs, Fauna/Serialization/PageDeserializer.cs, README.md
We want to expose support for calling User-Defined Functions via LINQ.
Collections and Indexes return sets whereas Functions can return anything. We could approach this a few ways, but I chose to make the existing QuerySource implementation work for functions. As such, the type declarations for functions are a little counter intuitive. Developers must type the Function based on the _element_ type it returns. For example, if it returns a single value, `T` in `Function<T>` must be that type. If it returns an array or set, the `T` must be the type of the element in the array or set.
E.g. 1: If a function returns a string, the type definition must be `Function<string>`. The caller may call `.Single()` to get a single value back, or `.ToList()` to get a list with a single element. 
E.g. 2: If …
=> Add Function support to LINQ DSL

Fauna.Test/Helpers/TestClientHelper.cs, Fauna.Test/Integration.Tests.cs, Fauna.Test/StatsCollector.Tests.cs, Fauna/Client/Client.cs, Fauna/Client/Configuration.cs, Fauna/Client/StatsCollector.cs, Fauna/Response/QueryStats.cs
Uses need a way to retrieve the query stats that are returned for both standard queries and when using Pagination
- Add a `StatsCollector` to the `Client`
=> Add StatsCollector to Client

Fauna.Test/Integration.Tests.cs, Fauna.Test/Linq/Context.Tests.cs, Fauna.Test/Linq/ContextValidation.Tests.cs, Fauna.Test/Linq/Query.Tests.cs, Fauna/Linq/DataContext.cs
Using null-forgiving operator to silence Rider errors:
Also renamed some vars:
=> Use null-forgiving init to silence errors in Rider

Fauna.Test/Serialization/RoundTrip.Tests.cs, Fauna.Test/Serialization/Serializer.Tests.cs, Fauna/Query/QueryVal.cs, Fauna/Serialization/ISerializer.cs, Fauna/Serialization/Serializer.cs, Fauna/Serialization/Serializers/CheckedSerializer.cs, Fauna/Serialization/Serializers/ClassSerializer.cs, Fauna/Serialization/Serializers/DictionarySerializer.cs, Fauna/Serialization/Serializers/DocumentSerializer.cs, Fauna/Serialization/Serializers/ListSerializer.cs, Fauna/Serialization/Serializers/ModuleSerializer.cs, Fauna/Serialization/Serializers/NullableDocumentSerializer.cs, Fauna/Serialization/Serializers/NullableSerializer.cs, Fauna/Serialization/Serializers/NullableStructSerializer.cs, Fauna/Serialization/Serializers/PageSerializer.cs, Fauna/Serialization/Serializers/StructSerializers.cs
* Use DynamicSerializer as default for type serializers
* Generate a type serializer for QueryVal.Serialize()
* Implement Serialize for all StructSerializers
* We can now implement Serialize for each type serializer with smaller PRs
* Prepares for the addition of a registry where users can call Serializer.Registry.Add(type, serializer) to be used in the serialize/deserialize paths.
* Existing tests pass
=> Use generated serializers for QueryVal serialization

README.md, concourse/scripts/publish-docs.sh
Ticket: [DOCS-3246](https://faunadb.atlassian.net/browse/DOCS-3246)
- We don't link to the driver API reference from the README. Users may not be aware these docs exist.
- I recently improved the API ref index. We need to update the build script to avoid overwriting the new index.
- I recently added a `latest/` symlink to the `gh-pages` branch that points to the latest release of the API ref. However, that symlink isn't updated as part of the release process.
----
[DOCS-3246]: https://faunadb.atlassian.net/browse/DOCS-3246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-3246] docs: Cross-link to driver API reference

Fauna/Client/Configuration.cs
Doxygen is unable to generate API ref docs for `Configuration.cs` without the `class` value type.
Per the [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record), `record` and `record class` are synonymous here.
I've already manually regenerated the 0.2.0-beta docs to fix this issue. This should fix it for future releases.
----
=> [DOCS-3248] bugfix: Fix API ref error

doc/Doxyfile
Updates the heading used in the driver API docs:
=> [DOCS-3249] docs: Update API docs heading

Fauna.Test/Serialization/Serializers/ClassSerializer.Tests.cs, Fauna.Test/Serialization/TestClasses.cs
Adding some more test coverage of the `MappingContext` and `FieldInfo` instantiation of serializers for built-in types, as well as a couple tests for duplicate field names.
More test coverage is a Good Thing.
Ran tests locally with `dotnet test --framework net8.0` - will let the GH Action validate net6.0.
* - [x] N/A (test only)
----
By submitting this pull request, I confirm that you can use, modify, …
=> Add more Serializer tests from the perspective of FieldInfos on the MappingContext

Fauna.Test/Integration.Tests.cs, Fauna/Core/Connection.cs
Stacked PR:
- #162 
Handle HTTP failure responses from Fauna
We're not currently handling non-200 responses from Fauna, consumers end up in an infinite loop.
Integration test included
----
=> feat(streaming): Handle failed requests

Fauna.Test/Integration.Tests.cs, Fauna/Core/Connection.cs, Fauna/Core/StreamEnumerable.cs, Fauna/Core/StreamOptions.cs, Fauna/IClient.cs, Fauna/Types/Stream.cs
Add `StreamOptions` to enable consumers to resume a Stream.
Consumers need to provide the `Token` and `Cursor` in order to resume a Stream. 
Included additional Integration Tests
----
=> feat(streaming): Add StreamOptions

Fauna.Test/Integration.Tests.cs, Fauna/Client.cs, Fauna/Core/Connection.cs, Fauna/Core/ResponseFields.cs, Fauna/Core/StreamEnumerable.cs, Fauna/Core/StreamOptions.cs, Fauna/IClient.cs, Fauna/Types/Event.cs, Fauna/Types/Stream.cs
Provide support for the new per-event stream cursor.
There's an edge case where resuming a stream from a txn time with lots of documents written could result in event loss. This approach fixes that edge case.
Updated integration test
----
=> feat(streams): Use Cursor

Fauna.Test/Exceptions/ServiceException.Tests.cs, Fauna/Types/Event.cs
Updated:
- Exception test cases (matched our JavaScript test cases)
- Exceptions thrown for Events
- We should be using `FaunaException` rather than HTTP Status Codes
- Exception types should be indicative of the failure 
- Updated test cases
----
=> feat: Updated Exceptions

Fauna.Test/Integration.Tests.cs, Fauna/Query/QueryArr.cs, Fauna/Query/QueryObj.cs, Fauna/Query/QueryStringHandler.cs, Fauna/Serialization/DictionarySerializer.cs, Fauna/Serialization/DynamicSerializer.cs, Fauna/Serialization/ListSerializer.cs, Fauna/Serialization/QueryArrSerializer.cs, Fauna/Serialization/QueryExprSerializer.cs, Fauna/Serialization/QueryLiteralSerializer.cs, Fauna/Serialization/QueryObjSerializer.cs, Fauna/Serialization/QuerySerializer.cs, Fauna/Serialization/QueryValSerializer.cs, Fauna/Serialization/Serializer.cs
Add Query fragment serialization to the `Serializer` 
- Add support for `QueryArr` and `QueryObj`
- Align serialization with other types
Included Integration tests
----
=> feat(serialization): Add Query fragments to Serializer

concourse/pipeline.yml, concourse/scripts/perf.sh
One more quick pipeline fix - Concourse can be a bit inscrutable.
----
=> fix(perf-tests): Concourse envvars don't propagate to subtask like I thought

README.md
- Fixes an error in the Event Streaming example (`StreamQueryAsync` should be `EventStreamAsync`).
- Adds a little more context about how to start and subscribe to a stream. 
----
=> [DOCS-3431] README: Fix Event Streaming example

Fauna.Test/Integration.Tests.cs, Fauna/Core/Connection.cs
Update `OpenStream` to use a `BlockingCollection`
We had a tight loop in the `EventListener` that was causing high CPU utilization
Integration tests and
<details>
<summary>Sandbox app</summary>
```csharp
using Fauna;
using Fauna.Mapping;
var client = new Client(Environment.GetEnvironmentVariable("FAUNA_SECRET")!);
var stream = await client.EventStreamAsync<Product>(Query.FQL($"Product.all().toStream()"));
var listenerLoop = Task.Run(async () =>
{
while (true)
{
Console.WriteLine("Waiting for events...");
await Task.Delay(TimeSpan.FromSeconds(15));
}
});
var eventsLoop = Task.Run(async () =>
{
await foreach (var evt in stream)
{
Console.WriteLine($"Received Event Type: {evt.Type}");
if (evt.Data != null)
{
Console.WriteLine($"Data: {evt.Data.Name}");
}
}
});
await …
```
=> fix(event-streams): CPU Utilization

Fauna.Test/Performance/Performance.Tests.cs, Fauna.Test/Performance/TestDataModels.cs, Fauna.Test/Performance/setup/queries.json
When a perf test is going to paginate, it will now paginate via three different methods: using `client.QueryAsync()` with the `after` token; using `PaginateAsync()`; and using `FlattenAsync()`.  Also, when reporting metrics on the overhead, it will now divide by the number of queries observed in the `StatsCollector` to make comparing the various query perf numbers clearer.
Ran it a number of times locally; the new output will automatically be picked up and sent to #alerts-driver-perf in Slack.
* - [ ] My change requires a change to Fauna …
=> chore(perf-tests): Improve perf metrics for paginating queries

Fauna.Test/Configuration.Tests.cs, Fauna/Client.cs, Fauna/Configuration.cs
Support using the `FAUNA_SECRET` env var when initializing the `Client`
All other versions of the driver support the `FAUNA_SECRET` env var
Additional tests included
----
=> feat: Client secret from env var

Fauna.Test/Configuration.Tests.cs, Fauna/Configuration.cs, Fauna/Core/Endpoints.cs
Support using the `FAUNA_ENDPOINT` env var when initializing the Client
All other versions of the driver support the `FAUNA_ENDPOINT` env var
Additional tests included
----
=> feat: Client endpoint from env var

Fauna.Test/E2E/E2ELinq.Test.cs, Fauna/IClient.cs
* Add IClient.LoadRefAsync<T>(BaseRef<T> reference) method. This will load a ref by querying Fauna, or return the loaded value if it's already present.
BT-5137
If a user has a reference to a document, allow a low effort way of materializing it.
Add e2e tests
* - [X] New feature (non-breaking change that adds functionality)
----
=> feat: Add client method to handle loading a ref

README.md
* Documents the `FAUNA_SECRET` env var default.
* Fixes formatting for POCO attributes docs in the README
* Document changes in https://github.com/fauna/fauna-dotnet/pull/178.
* Fixes some README formatting.
Tested locally
----
=> [DOCS-3539] docs: Document `FAUNA_SECRET` env var default

Fauna.Test/Integration.Tests.cs, Fauna/Serialization/DynamicSerializer.cs
Terminate dynamic ref deserialization on EndDocument token
We farm out the doc deserialization and end on an EndDocument token, then advance the token stream before checking if we are at the end of the document.
Added unit test.
----
=> fix: dynamic ref deser ends at wrong token

Fauna.Test/Util/Logging.Tests.cs, Fauna/Configuration.cs, Fauna/Core/Connection.cs, Fauna/Fauna.csproj, Fauna/Util/Logger.cs, README.md
BT-5158
This change adds support for additional debug/trace logging in the driver via `Microsoft.Extensions.Logging.ILogger` interface.  Consumers of the driver can set the `FAUNA_DEBUG` environment variable to `0` or `1` (higher is _less_ verbose in .NET log-levels, so 2+ won't output anything at the moment), which will cause the new `Logger` static class to instantiate a default `ILogger` implementation that writes all messages to `stderr` (to avoid polluting `stdout` for consumers).  At present, the driver will output details about the HTTP request and response to/from Fauna with the `Authorization` header value redacted for security reasons.
However, if consumers want to bring their own `ILogger` implementation (i.e. Serilog), they can pass it to the `Configuration` class when …
=> feat(logging): Add support for ILogger-based debug logging, including BYO

Fauna.Test/Integration.Tests.cs, Fauna.Test/Serialization/Serializers/TypedSerializer.Tests.cs, Fauna.Test/Serialization/TestClasses.cs, Fauna/Linq/Deserializers.cs, Fauna/Serialization/BaseRefSerializer.cs, Fauna/Serialization/ClassSerializer.cs, Fauna/Serialization/DictionarySerializer.cs, Fauna/Serialization/DynamicSerializer.cs, Fauna/Serialization/FaunaType.cs, Fauna/Serialization/ISerializer.cs, Fauna/Serialization/ListSerializer.cs, Fauna/Serialization/ModuleSerializer.cs, Fauna/Serialization/NullableSerializer.cs, Fauna/Serialization/NullableStructSerializer.cs, Fauna/Serialization/PageSerializer.cs, Fauna/Serialization/Serializer.cs, Fauna/Serialization/StreamSerializer.cs, Fauna/Serialization/StructSerializers.cs, Fauna/Serialization/TokenType.cs
BT-5115
Pursuant to the ticket, we want to make deserialization errors easier to reason about; the current changes are based on a similar fix in the `fauna-jvm` driver here: https://github.com/fauna/fauna-jvm/pull/129
The change ultimately is an improvement on the `SerializationException` message to avoid spitting out the unexpected token received on the wire from Fauna and instead mapping that token to the expected `FaunaType` (a new enum) that should help point consumers to the issue in their logic where they are expecting to deserialize as one type but the .NET driver's serialization logic saw a different type.  Tests have been updated and a couple new ones were added.
See above.
I used new test automation to repeatedly validate the changes with various tweaks until I liked the final …
=> chore(serialization): Improve deserialization errors

Fauna.Test/Integration.Tests.cs, Fauna.Test/Serialization/Helpers.cs, Fauna.Test/Serialization/Serializers/TypedSerializer.Tests.cs, Fauna.Test/Serialization/Utf8FaunaReader.Tests.cs, Fauna.Test/Serialization/Utf8FaunaWriter.Tests.cs, Fauna/Serialization/DynamicSerializer.cs, Fauna/Serialization/Serializer.cs, Fauna/Serialization/StructSerializers.cs, Fauna/Serialization/TokenType.cs, Fauna/Serialization/Utf8FaunaReader.cs, Fauna/Serialization/Utf8FaunaWriter.cs
While working on a previous change, I noticed that we didn't have explicit support for the `@bytes` tag, so this adds it.
See above.  Tracked in ticket BT-5183
Ran the code through new tests with `FAUNA_DEBUG=0`; all tests (including new ones) are green
----
=> feat(serialization): Add support for @bytes tag

Fauna.Test/Serialization/Utf8FaunaReader.Tests.cs, Fauna/Serialization/Utf8FaunaReader.cs
* Handle unmaterialized set endings by tracking an internal token type on the stack and buffering the value
* Handle unmaterialized set tokens by buffering the value. This is the first case where we need to buffer a token that has an associated value. This implementation is naive, but that's intentional due to time constraints.
BT-5260
Materialized and unmaterialized sets look slightly different on the wire. In the case of materialized sets, we encounter two end object json tokens that represent the end of the set. In the unmaterialized case, we only encounter one. When the reader encounters the unmaterialized set, it will cause the token stream to be shifted by one.
Added unit test covering the scenario.
* - [ ] New feature …
=> fix: Handle unmaterialize set endings in UTF8FaunaReader

README.md
Updates the README's streaming section to use:
* New CDC terminology (`stream token` -> `event source`)
* New `eventSource()` and `eventsOn()` FQL methods
This aligns the README with the latest terminology in the docs and FQL.
N/A
----
=> [DOCS-3658] docs: Update CDC terminology in README

README.md
Fixes a typo in the README's Event Streaming example.
- `toStream()` is deprecated and has been replaced by `eventSource()`
- The current example is missing parentheses and is invalid
Tested locally.
----
=> [DOCS-3362] docs: Fix typo in streaming example

Fauna.Test/Configuration.Tests.cs, Fauna/Client.cs, Fauna/Configuration.cs, Fauna/Core/Connection.cs, Fauna/Core/IConnection.cs, Fauna/Core/QueryOptions.cs
To date the `HttpClient.Timeout` was set to 5 seconds, which could be overridden when instantiating the `HttpClient`, but it was clunky to override after the fact.  Upon realizing this, I noticed that we lacked support for a `queryTimeoutBuffer` that we have in other drivers, where the HTTP request timeout is actually the sum of the `queryTimeoutMs` for the given query plus a `queryTimeoutBuffer` that defaults to 5 seconds, so the default case would be 10 seconds total.  This PR adds that.
I'll grant that the way we configure the Fauna `Client` and the `HttpClient` is a little convoluted, so this PR attempts to make it work as is, but maybe a refactor would make the interface a little clearer.  I'm open to feedback on that.
NB: This is a slightly breaking change because it does change the …
=> chore(client): Add support for query timeout buffer (port from JVM)

Fauna/Core/StreamOptions.cs, Fauna/Types/Module.cs
* Fixes some Doxygen warnings
* Updates several links to the CDC docs
[DOCS-3671](https://faunadb.atlassian.net/browse/DOCS-3671)
Currently, Doxygen is just dropping the syntax from these warnings.
Ran Doxygen locally.
----
[DOCS-3671]: …
=> chore: Fix Doxygen warnings

concourse/pipeline.yml
This PR adds support for validating the .NET driver in Azure Functions to ensure that a release build doesn't break one of the most popular 3rd-party platform that .NET customers would likely use for serverless functions.
The pipeline references a private repo, `fauna/testtools`, which just contains a simple Hello World app and the script collateral needed to publish the Azure Function app.
BT-4442
Tested the setup scripts, test case, and Dockerfile build locally against real Azure; the image build part of the pipeline may require some iteration.
* …
=> feat(platform-tests): Add 3rd-party platform testing to the release pipeline

.github/workflows/pr_validate.yml, Fauna.Test/Fauna.Test.csproj, Fauna/Fauna.csproj, README.md
As discussed, we're removing `net6.0` support as it is coming out of official Microsoft support in just a few days from this PR: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
BT-5277
Built the project and ran automation; no other changes
* - [x] Breaking change (backwards-incompatible fix or feature)
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> chore: Remove official net6.0 support

concourse/pipeline.yml
The Azure Function tools only build on amd64 (🤦), so I need to skip the arm64 build; fortunately (but not before several hours not realizing this fact), our Concourse workers are Intel-based, so amd64 is all we need for now.
BT-5290
I had already been able to build amd64 locally and in the pipeline; this just removes the arm64 build.
----
By submitting this pull request, I confirm that you can use, modify, …
=> chore(platform-tests): Build Dockerfile.dotnet in only amd64

Fauna.Test/Integration.Tests.cs, Fauna/Client.cs, Fauna/Core/Connection.cs, Fauna/Core/FeedEnumberable.cs, Fauna/Core/FeedOptions.cs, Fauna/Core/FeedPage.cs, Fauna/Core/ResponseFields.cs, Fauna/Core/StreamOptions.cs, Fauna/IClient.cs, Fauna/Linq/DataContext.cs, Fauna/Types/Event.cs, Fauna/Types/EventSource.cs
BT-5171
Add support for [Event Feeds](https://docs.fauna.com/fauna/current/learn/track-changes/streaming/#change-feeds)
Feature parity 
Unit Tests included
----
=> feat: Event Feeds

Fauna.Test/Integration.Tests.cs, Fauna/Exceptions/EventException.cs, Fauna/Types/Event.cs
BT-5300
Add Exception type for errors raised with Event Streams or Event Feeds
Enable to consumers to catch errors for specific failure cases
Updated integ tests
----
=> feat: Add Exception type for Event errors

Fauna.Test/Integration.Tests.cs, Fauna/Core/QueryStats.cs, Fauna/Core/ResponseFields.cs
BT-4680
Add support for the `processing_time_ms` stat returned on Events
Include all available Stats
Updated integ test
----
=> feat: Add Processing Time stat field

README.md
Updates the README for https://github.com/fauna/fauna-dotnet/pull/211/.
Keep the README updated.
Tested locally.
----
=> docs: Add event feeds to README

Fauna.Test/Integration.Tests.cs, Fauna/Core/FeedEnumerable.cs, README.md
- Remove the `NextAsync` method from the `FeedEnumerable`
- Fix typo on the file name
A few consumers have stubbed their toe on this method appearing to something that can be used in a `while`. We don't need it as consumers can manually step through the enumerator returned from `GetAsyncEnumerator` if they so choose. 
Validated integ tests
----
By submitting this pull request, I confirm that you can use, …
=> fix: Remove NextAsync from FeedEnumerable

README.md
Updates the README to remove references to driver beta.
Prepare the README for GA release.
See [DOCS-3692](https://faunadb.atlassian.net/browse/DOCS-3692).
N/A
----
[DOCS-3692]: https://faunadb.atlassian.net/browse/DOCS-3692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
=> docs: Update README for GA release

Fauna.Test/Serialization/Serializers/DynamicSerializer.Tests.cs, Fauna/Serialization/DynamicSerializer.cs
Handle event source deserialization with the DynamicSerializer
BT-5312
If you request an event source from Fauna without specifying a return type, we use the DynamicSerializer to deserialize the results. In this case, we encountered an unsupported token exception.
Added unit test
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Handle event sources in DynamicSerializer

Fauna.Test/Configuration.Tests.cs, Fauna.Test/Connection.Tests.cs, Fauna/Client.cs, Fauna/Configuration.cs
BT-5323
Move `Configuration` validation into a new public method
Consumers are unable to produce a Configuration with an object initializer because we validate within the constructor. 
Updated tests
----
=> feat: Update Config validation

Fauna/Core/FeedOptions.cs
Documents accepted range for `pageSize` in `FeedOptions`.
Keeps docs updated with changes in https://github.com/fauna/core/pull/12010.
N/A
----
=> [DOCS-3753] Event Feeds: Document `pageSize` limit
